name: Test
run-name: Test the project on macOS and Ubuntu
on: [push]
jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run make test
        run: make test
      - name: Run the test
        run: ./test_sum

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run make test
        run: make test
      - name: Run the test
        run: ./test_sum
