CC = g++
CFLAGS = -Wall -Wextra -std=c++17

all: add1 add2 add3

add1: add1.cpp
	$(CC) $(CFLAGS) -o add1 add1.cpp

add2: add2.cpp
	$(CC) $(CFLAGS) -o add2 add2.cpp

add3: add3.cpp
	$(CC) $(CFLAGS) -o add3 add3.cpp

clean:
	rm -f add1 add2 add3